# Generated by Django 5.1 on 2024-09-30 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onco', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
    ]
