# Generated by Django 5.1 on 2024-10-04 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onco', '0002_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user',
            new_name='Usuario',
        ),
    ]
