# Generated by Django 5.1 on 2024-10-04 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onco', '0003_rename_user_usuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='password',
            new_name='contra',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='username',
            new_name='nombre',
        ),
    ]
