# Generated by Django 5.1.1 on 2024-10-09 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onco', '0005_delete_usuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patientdata',
            old_name='ALCOHOL_CONSUMING',
            new_name='Alergia',
        ),
        migrations.RenameField(
            model_name='patientdata',
            old_name='ALLERGY',
            new_name='Ansiedad',
        ),
        migrations.RenameField(
            model_name='patientdata',
            old_name='ANXIETY',
            new_name='Consumo_de_alcohol',
        ),
        migrations.RenameField(
            model_name='patientdata',
            old_name='ANXYELFIN',
            new_name='Dedos_amarillos',
        ),
        migrations.RenameField(
            model_name='patientdata',
            old_name='CHEST_PAIN',
            new_name='Dificultad_para_tragar',
        ),
        migrations.RenameField(
            model_name='patientdata',
            old_name='CHRONIC_DISEASE',
            new_name='Dolor_en_el_pecho',
        ),
        migrations.RenameField(
            model_name='patientdata',
            old_name='COUGHING',
            new_name='Edad',
        ),
        migrations.RenameField(
            model_name='patientdata',
            old_name='FATIGUE',
            new_name='Enfermedad_crónica',
        ),
        migrations.RenameField(
            model_name='patientdata',
            old_name='PEER_PRESSURE',
            new_name='Fatiga',
        ),
        migrations.RenameField(
            model_name='patientdata',
            old_name='name',
            new_name='Nombre',
        ),
        migrations.RenameField(
            model_name='patientdata',
            old_name='SWALLOWING_DIFFICULTY',
            new_name='Presión_de_pares',
        ),
        migrations.RenameField(
            model_name='patientdata',
            old_name='WHEEZING',
            new_name='Sibilancias',
        ),
        migrations.RenameField(
            model_name='patientdata',
            old_name='YELLOW_FINGERS',
            new_name='Tos',
        ),
        migrations.RemoveField(
            model_name='patientdata',
            name='age',
        ),
        migrations.RemoveField(
            model_name='patientdata',
            name='gender',
        ),
        migrations.AddField(
            model_name='patientdata',
            name='Genero',
            field=models.CharField(choices=[('H', 'Hombre'), ('M', 'Mujer')], default=' ', max_length=1),
            preserve_default=False,
        ),
    ]
