# Generated by Django 5.1.1 on 2024-11-08 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onco', '0006_rename_alcohol_consuming_patientdata_alergia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientdata',
            name='probability',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
