# Generated by Django 5.1.1 on 2024-11-21 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onco', '0007_alter_patientdata_probability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientdata',
            name='Genero',
            field=models.CharField(choices=[('H', 'Hombre'), ('M', 'Mujer'), ('O', 'Otros'), ('P', 'Prefiero no decirlo')], max_length=1),
        ),
    ]
